

services:
  web:
    image: crud-laravel:latest
    build:
      target: web
      context: .
    env_file:
      - .env
    ports:
      - "8000:80"
    volumes:
      - ./apache_configs:/etc/apache2/sites-available
    depends_on:
      - db
  
  db:
    platform: "linux/amd64"
    image: mysql:5.7
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: ${app-crud}
      MYSQL_USER: ""
      MYSQL_PASSWORD: ""
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata: